name: "Gradle Build"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  GradleBuild:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Unit Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/testCoverage/testCoverage.xml
          min-coverage-overall: 40
          min-coverage-changed-files: 60
